### ISSUE TITLE
[audible] API 

### ISSUE THREAD

**Issue by nullbasis** [89z/mech#14]
Thanks for this project, it looks to be super useful.

Anyway, as per [this issue in youtube-dl](https://github.com/ytdl-org/youtube-dl/issues/28317), I'm opening this issue.

**Comment by 89z** [comment]
Thanks for the post. I am very busy [1], but I will see if I can move Audible to the top of the list.

1. https://github.com/89z/mech/tree/master/research

**Comment by 89z** [comment]
Can you please provide an example URL? It seems the one in the other issue is a paid item.

**Comment by 89z** [comment]
Closing this now. If you are able to respond, I can reopen, thanks

**Comment by nullbasis** [comment]
Sorry, I wasn't able to get to it yesterday. This one appears to be free: https://www.audible.com/pd/Go-the-F-k-to-Sleep-Audiobook/B00551W570

**Comment by 89z** [comment]
looks good, I will work on this. Final solution might work for paid items as well, but I am going to start with free items

**Comment by 89z** [comment]
I think I am going to have to pass on this. The media files are not encrypted, and just need a simple GET request. However they are hidden behind an elaborate login process. An implementation of the iOS login [1] is available, but it even seems to require a captcha. I was able to successfully login like this:

~~~py
from audible import Authenticator

auth = Authenticator.from_login(
    username="srpen6@gmail.com",
    password="myPassword",
    locale="us",
)

print(auth)
~~~

Its possible the Android client doesnt need a Captcha, but regardless of the approach it would like a lot of time. As I dont use the site myself currently, because of the time involved, I would only be willing to implement it if someone sent me a donation. If thats your sitatuion, let me know. Otherwise good luck to you.

1. https://github.com/mkb79/Audible

**Comment by 89z** [comment]
I am going to take another crack at this. I cant promise anything, but we will see.

**Comment by 89z** [comment]
I found a way to bypass the CAPTCHA:

~~~
https://www.amazon.com/ap/signin?
openid.assoc_handle=amzn_audible_android_aui_us&
openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&
openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&
openid.mode=checkid_setup&
openid.ns.oa2=http%3A%2F%2Fwww.amazon.com%2Fap%2Fext%2Foauth%2F2&
openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&
openid.oa2.client_id=device%3A3738656232643031306334623466323238346237234131304b49535032475746304534&
openid.oa2.code_challenge=FqnF5AR7EuNjawwfQ2f757HcSMrEej9V3GqSsyzWS9Q&
openid.oa2.response_type=code&
openid.oa2.scope=device_auth_access
~~~

Its still going to take a lot more work, but this is promising...

**Comment by 89z** [comment]
Sorry, I am going to close this again for now. I do think I am able to complete it, but its going to be tough, and I am prioritizing other stuff right now. So unless someone wants to make a donation in service of this issue, I will pick it up at a later time.

**Comment by 89z** [comment]
Reopening this again. Not sure if I will be able to work on it right away, but I do have some free time now, so maybe.

**Comment by 89z** [comment]
I apologize for the back and forth, but I think I am going to close this for good. I would quite like to punish Amazon by implementing this, but on the other hand, I don't really have a use for the site myself. If someone is willing to make a donation, I would be willing to work on this.
